[versions]
jvmTarget = "11"

[libraries]
assertj = "org.assertj:assertj-core:3.27.3"
jimfs = "com.google.jimfs:jimfs:1.3.1"
junitJupiter = "org.junit.jupiter:junit-jupiter:5.11.4"
junitPlatformLauncher = "org.junit.platform:junit-platform-launcher:1.11.4"
tomlj = "org.tomlj:tomlj:1.1.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
