name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_version.outputs.version }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Extract release version
        id: release_version
        run: |
          VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | xargs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate tag matches release version
        env:
          REFNAME: ${{ github.ref_name }}
        run: |
          if [[ "$REFNAME" != "${{ steps.release_version.outputs.version }}" ]]; then
            echo "Error: Tag '$REFNAME' does not match expected version '${{ steps.release_version.outputs.version }}'."
            exit 1
          fi

  publish:
    needs: release_version
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SECRET_PASSPHRASE }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # v1.1.4
      - run: bin/gradle publishToMavenCentral --no-configuration-cache
